name = "tradeos-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "TRADEOS_USERS"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_CACHE"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_PLAYBOOK"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_WATCHLIST"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_ALERTS"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_JOURNAL"
id = "aae1638fc4d144f0a8accd0cd956a7bc"

[[kv_namespaces]]
binding = "TRADEOS_PERFORMANCE"
id = "aae1638fc4d144f0a8accd0cd956a7bc"